# Generated by Django 6.0.6 on 2026-06-27 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoisBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Mois et Année (ex: Juillet 2026)')),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_cloture', models.BooleanField(default=False, verbose_name='Mois clôturé ?')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_donateur', models.CharField(max_length=100, verbose_name='Nom du donateur')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('date_don', models.DateField(default=django.utils.timezone.now)),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='caisse.moisbudget')),
            ],
        ),
        migrations.CreateModel(
            name='AideBeneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_beneficiaire', models.CharField(max_length=100, verbose_name='Nom du bénéficiaire')),
                ('montant_accorde', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant accordé (€)')),
                ('cause', models.TextField(verbose_name="Cause de l'aide")),
                ('cree_le', models.DateField(default=django.utils.timezone.now)),
                ('mois', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aide', to='caisse.moisbudget')),
            ],
        ),
    ]
