# Generated by Django 6.0.6 on 2026-06-28 04:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='mois',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('VERSEMENT', 'Versement (Cotisation)'), ('RETRAIT', 'Retrait (Aide accordée)')], default='VERSEMENT', max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (MRU)')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_concernee', models.IntegerField(blank=True, null=True, verbose_name='Année concernée')),
                ('mois_couverts', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mois couverts (ex: Janvier, Février)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name="Détails / Bénéficiaire de l'aide")),
                ('actif', models.BooleanField(default=True, verbose_name='Transaction active (incluse dans le total)')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='caisse.membre', verbose_name='Membre (si versement)')),
            ],
        ),
        migrations.DeleteModel(
            name='AideBeneficiaire',
        ),
        migrations.DeleteModel(
            name='Cotisation',
        ),
        migrations.DeleteModel(
            name='MoisBudget',
        ),
    ]
